apiVersion: apps/v1
kind: Deployment
metadata:
  name: xtb
  namespace: brokers
  labels:
    app: xtb
    keel.sh/policy: force
spec:
  replicas: 1
  selector:
    matchLabels:
      app: xtb
  template:
    metadata:
      labels:
        app: xtb
    spec:
      containers:
        - name: xtb
          image: joeburnardredbrain/kwont:xtb_broker-latest
          imagePullPolicy: Always
          args:
            - --level=debug
            - --amqp-address=amqp://user:pass@rabbitmq.default:5672/
            - --router-address=xtb-router.brokers:8080
          resources:
            requests:
              cpu: 50m
              memory: 100M
            limits:
              cpu: 100m
              memory: 200M
          volumeMounts:
            - name: "cacerts"
              mountPath: "/etc/ssl/cacerts"
              readOnly: true
          env:
            - name: POD_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP
      volumes:
        - name: "cacerts"
          hostPath:
            path: "/etc/ssl/certs"
