kind: Service
apiVersion: v1
metadata:
  name: xtb
  namespace: brokers
  labels:
    name: xtb
spec:
  type: NodePort
  selector:
    app: xtb
  ports:
    - targetPort: 8080
      protocol: TCP
      port: 8080