apiVersion: apps/v1
kind: Deployment
metadata:
  name: xtb-router
  namespace: brokers
  labels:
    app: xtb-router
    keel.sh/policy: force
spec:
  replicas: 1
  selector:
    matchLabels:
      app: xtb-router
  template:
    metadata:
      labels:
        app: xtb-router
    spec:
      containers:
        - name: xtb
          image: joeburnardredbrain/kwont:router-latest
          imagePullPolicy: Always
          args:
            - --level=debug
          resources:
            requests:
              cpu: 50m
              memory: 100M
            limits:
              cpu: 100m
              memory: 200M
          volumeMounts:
            - name: "cacerts"
              mountPath: "/etc/ssl/cacerts"
              readOnly: true
      volumes:
        - name: "cacerts"
          hostPath:
            path: "/etc/ssl/certs"
