apiVersion: apps/v1
kind: Deployment
metadata:
  name: session-checker
  namespace: brokers
  labels:
    app: xtb-session-checker
    keel.sh/policy: force
spec:
  replicas: 1
  selector:
    matchLabels:
      app: xtb-session-checker
  template:
    metadata:
      labels:
        app: xtb-session-checker
    spec:
      containers:
        - name: xtb-session-checker
          image: joeburnardredbrain/kwont:session_checker-latest
          imagePullPolicy: Always
          args:
            - --level=debug
            - --dataservice-address=dataservice.data:8080
            - --router-address=xtb-router.brokers:8080
            - --broker-name=XTB_DEMO
            - --poll-interval-seconds=15
          resources:
            requests:
              cpu: 50m
              memory: 100M
            limits:
              cpu: 100m
              memory: 200M
          volumeMounts:
            - name: "cacerts"
              mountPath: "/etc/ssl/cacerts"
              readOnly: true
      volumes:
        - name: "cacerts"
          hostPath:
            path: "/etc/ssl/certs"
