apiVersion: apps/v1
kind: Deployment
metadata:
  name: dataservice
  namespace: data
  labels:
    app: dataservice
    keel.sh/policy: force
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dataservice
  template:
    metadata:
      labels:
        app: dataservice
    spec:
      containers:
        - name: dataservice
          image: joeburnardredbrain/kwont:dataservice-latest
          imagePullPolicy: Always
          args:
            - --level=debug
          resources:
            requests:
              cpu: 50m
              memory: 100M
            limits:
              cpu: 100m
              memory: 200M
          volumeMounts:
            - name: "cacerts"
              mountPath: "/etc/ssl/cacerts"
              readOnly: true
      volumes:
        - name: "cacerts"
          hostPath:
            path: "/etc/ssl/certs"
