apiVersion: apps/v1
kind: Deployment
metadata:
  name: trade-status-writer
  namespace: data
  labels:
    app: trade-status-writer
    keel.sh/policy: force
spec:
  replicas: 1
  selector:
    matchLabels:
      app: trade-status-writer
  template:
    metadata:
      labels:
        app: trade-status-writer
    spec:
      containers:
        - name: trade-status-writer
          image: joeburnardredbrain/kwont:trade_status_writer-latest
          imagePullPolicy: Always
          args:
            - --level=debug
            - --amqp-address=amqp://user:pass@rabbitmq.default:5672/
            - --topic=xtb-trade-status
            - --broker=XTB_DEMO
            - --dataservice-address=dataservice.data:8080
          resources:
            requests:
              cpu: 50m
              memory: 100M
            limits:
              cpu: 100m
              memory: 200M
          volumeMounts:
            - name: "cacerts"
              mountPath: "/etc/ssl/cacerts"
              readOnly: true
      volumes:
        - name: "cacerts"
          hostPath:
            path: "/etc/ssl/certs"
