name: Go

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:

    - name: Set up Go 1.12
      uses: actions/setup-go@v1
      with:
        go-version: 1.12
      id: go

    - name: Check out code into the Go module directory
      uses: actions/checkout@v2

    - name: list it
      run: ls

    - name: pwd it
      run: pwd

    - name: Build XTB Broker
      run: GO111MODULE=on CGO_ENABLED=0 GOOS=linux go build -mod=vendor -o kwont "./cmd/xtb_broker/main.go"

    - name: Upload Artifact
      uses: actions/upload-artifact@v1
      with:
        name: kwont
        path: ./kwont

    - name: Build XTB Broker Docker Image
      run: docker build -t xtb_broker:latest -f Dockerfile .
