name: Go

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:

    - name: Set up Go 1.12
      uses: actions/setup-go@v1
      with:
        go-version: 1.12
      id: go

    - name: list it
      run: ls

    - name: pwd it
      run: pwd

    - name: Build XTB Broker
      run: GO111MODULE=on GOFLAGS= CGO_ENABLED=0 GOOS=linux go build -o kwont "./cmd/xtb_broker/main.go"
